spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    static-path-pattern: /**

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  web:
    resources:
      static-locations: classpath:static/

